### ISSUE TITLE
Error: unrecognized arguments: mysql

### ISSUE THREAD

**Issue by shoughun** [dennishafemann/import-sql-to-couch#1]
I tried doing this on the command line under the import-sql-to-couch-master folder -> python import_sql_2_couch.py -s http://username:password@localhost -c http://username:password@127.0.0.1 -ss phdraft -st mysql

and it gives me this error.

usage: import_sql_2_couch.py -s SQL_CONNECTION [-ss SQL_SOURCES]
                             [-sl SQL_LIMIT] [-scsql SQL_CONNECT_SQL] -c
                             COUCH_CONNECTION [-cct {db_tbl,db,tbl}] [-adbi]
                             [-adbin ADD_DATABASE_INFO_NAME] [-atbi]
                             [-atbin ADD_TABLE_INFO_NAME] [-v] [-d] [-h]
import_sql_2_couch.py: error: unrecognized arguments: mysql

Hope you can help me out. Thanks in advance.

**Comment by dennishafemann** [comment]
Well, actually, there is no -st parameter you used to give the "type" mysql, i guess. Take a look a the --help documentation. It says that the -s parameter holds the "sqlalchemy-database-dialect" as the protocol:

[sqlalchemy-database-dialect://][username:password@]sql-host[:port]

So, try ...

import_sql_2_couch.py -s mysql://username:password@localhost -c http://username:password@127.0.0.1 -ss phdraft

I hope this helps you out.

cya

**Comment by shoughun** [comment]
Connection is working now. Thanks. ;)
