### ISSUE TITLE
Cannot write document to couch

### ISSUE THREAD

**Issue by shoughun** [dennishafemann/import-sql-to-couch#2]
After running the script I get this error.
Document:  {u'extension_name': 'Ronel', u'countMe': 4831L, u'farmer_name': 'Mary
 Rose Opa\xc3\xb1o', u'ref_id': 37517L}
Error: Cannot write document to couch.

Also, when I check in the futon GUI. it seems that this script is creating one database per table. e.g. databasename1_tablename1, databasename1_tablename2. Is this really how it works? Thank again. ;)

**Comment by dennishafemann** [comment]
With parameter -cct or --couch-creation-type you can define you the databse/table should be created. You should give it a try, for there is a default for this parameter:

https://github.com/dennishafemann/import-sql-to-couch#couch-creation-type.
